{
  try {
    return doEval(env);
  }
 catch (  EvalException|RuntimeException ex) {
    throw handleException(ex);
  }
}
