{
  try {
    failAction.execute(null);
    fail();
  }
 catch (  ActionExecutionException e) {
    assertThat(e).hasMessage(errorMessage);
  }
}
