def set_exception(self, exception):
    'Sets the result of the future as being the given exception.\n\n        Should only be used by Executor implementations and unit tests.\n        '
    with self._condition:
        self._exception = exception
        self._state = FINISHED
        for waiter in self._waiters:
            waiter.add_exception(self)
        self._condition.notify_all()
    self._invoke_callbacks()
