{
  try {
    builder.build();
    fail("Expected exception");
  }
 catch (  Exception e) {
    assertThat(e).hasMessage(expected);
  }
}
