{
  return Truth.assertThat(getSubject().getException()).named("Exception in " + getDisplaySubject());
}
