{
  try {
    waitAndMaybeThrowInterrupt(latch,errorMessage);
  }
 catch (  Throwable e) {
    exceptionsThrown.add(Pair.of(errorMessage,e));
    Throwables.propagate(e);
  }
}
