{
  try {
    command.execute(Command.NO_INPUT,Command.NO_OBSERVER,System.out,System.err,true);
    fail("Subprocess not aborted!");
  }
 catch (  AbnormalTerminationException e) {
    assertEquals("Process terminated by signal 15",e.getMessage());
  }
  assertDuration(1000,1500);
  assertTrue("Main thread was not interrupted during command execution!",mainThread.isInterrupted());
}
