{
  Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler(){
    @Override public void uncaughtException(    Thread thread,    Throwable throwable){
      try {
        BugReport.handleCrash(throwable,args);
      }
 catch (      Throwable t) {
        System.err.println("An exception was caught in " + Constants.PRODUCT_NAME + "'s "+ "UncaughtExceptionHandler, a bug report may not have been filed.");
        System.err.println("Original uncaught exception:");
        throwable.printStackTrace(System.err);
        System.err.println("Exception encountered during UncaughtExceptionHandler:");
        t.printStackTrace(System.err);
        Runtime.getRuntime().halt(BugReport.getExitCodeForThrowable(throwable));
      }
    }
  }
);
}
