{
  try {
    super.invalidateObject(key,obj);
  }
 catch (  Throwable t) {
    Throwables.propagateIfPossible(t,IOException.class,InterruptedException.class);
    throw new RuntimeException("unexpected",t);
  }
}
