{
  try {
    execute(argsArray,wrapper,true);
  }
 catch (  CommandFailedException e) {
    handleException(e);
  }
}
